[package]
name = "basalt-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Basalt launcher desktop GUI"

[dependencies]
basalt-core.workspace = true
crossbeam-channel = "0.5"
eframe = "0.31"
gilrs = "0.11"
image.workspace = true
resvg.workspace = true

[build-dependencies]
ico = "0.4"
resvg.workspace = true

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
